import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"; // Import DM_Sans
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] }); // Create DM_Sans instance

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}> {/* Apply DM Sans class */}
        {children}
      </body>
    </html>
  );
}

